import {ThemeProvider} from "@/components/providers/theme-provider";
import "./globals.css";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import Topbar from "@/components/shared/navigation/Topbar";
import ConditionallyRenderLeftSidebar from "@/components/shared/navigation/ConditionallyRenderLeftSidebar";
import ConditionallyRenderRightSidebar from "@/components/shared/navigation/ConditionallyRenderRightSidebar";
import Bottombar from "@/components/shared/navigation/Bottombar";
import RightSidebar from "@/components/shared/navigation/RightSidebar";
import LeftSidebar from "@/components/shared/navigation/LeftSidebar";
import LeftsidebarWrapper from "@/components/shared/navigation/LeftsidebarWrapper";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Topbar />
          <main className="flex flex-row">
            <LeftsidebarWrapper />
            <section className="main-container">{children}</section>
            <ConditionallyRenderRightSidebar />
          </main>
          <Bottombar />
        </ThemeProvider>
      </body>
    </html>
  );
}
